### ISSUE TITLE
Légalement il faut maintenant le pdf officiel imprimé ou papier libre

### ISSUE THREAD

**Issue by ewjoachim** [magopian/att#11]
Le gouvernement a retro-pédalé:
https://www.numerama.com/politique/611777-attestation-de-deplacement-que-faire-sans-imprimante-ni-papier.html

Du coup... Bah le projet n'est plus utilisable.

**Comment by magopian** [comment]
Oui je viens de voir, cf aussi https://www.bfmtv.com/tech/confinement-finalement-l-attestation-sur-smartphone-ne-suffit-pas-1877104.html

Le site peut toujours être utilisé pour ensuite l'imprimer, mais auquel cas autant utiliser le PDF officiel... Je vais rajouter un gros bandeau en tête du site.

**Comment by bortzmeyer** [comment]
Et le tweet de la gendarmerie que cite le site Web a disparu.

**Comment by ewjoachim** [comment]
@magopian si tu veux repurposer le projet, tu peux faire un minisite accessible qui produit une version remplie du pdf officielle pour les personnes qui ne peuvent pas (handicap ou incompatibilité logicielle) remplir le PDF.

**Comment by magopian** [comment]
yep, je vais indiquer en en-tête qu'il faut l'imprimer pour que ce soit valable

**Comment by ewjoachim** [comment]
@magopian c'est pas juste l'imprimer, il faut que ce soit le PDF officiel :/

**Comment by magopian** [comment]
Je vois pas comment c'est possible, vu que l'autre solution c'est de le recopier en manuscrit. Tu me dis que l'imprimer serait pas recevable non plus ?!

**Comment by magopian** [comment]
J'ai mis à jour le site avec un header explicatif.

**Comment by ewjoachim** [comment]
Nan, ce que je comprends c'est qu'il faut soit le PDF officiel imprimé, soit un papier libre. Maintenant, on peut peut-etre réussir a faire un papier indiscernable du pdf officiel une fois imprimé.
