### ISSUE TITLE
Mise à jour du formulaire du gouvernement

### ISSUE THREAD

**Issue by lnplnp** [magopian/att#13]
Bonjour,

Depuis le 26/03/2020, le formulaire a changé.
Pourrais-tu adapter le code afin de prendre en compte le nouveau formulaire.
Tu trouveras la nouvelle version ici : https://www.interieur.gouv.fr/Actualites/L-actu-du-Ministere/Attestation-de-deplacement-derogatoire-et-justificatif-de-deplacement-professionnel

Pour moi, "issues" cela veut surtout dire "anomalies" ou "problème", est-ce bien par là que l'on demande une évolution via les "issues" ?

Merci.

**Comment by magopian** [comment]
Bonjour,

> Pour moi, "issues" cela veut surtout dire "anomalies" ou "problème", est-ce bien par là que l'on demande une évolution via les "issues" ?

Oui c'est un moyen comme un autre de communiquer sur les évolutions futures (modifications, améliorations, fix...)

Pour ta demande j'ai effectivement vu le changement, et je l'ai reflété dans la V2 : https://magopian.github.io/att/

Attention, la V2 tout comme la V1 ne sont pas recevables si j'ai bien compris. De recevable il n'y a que le PDF officiel imprimé ou la feuille manuscrite. Il me semble qu'il n'est pas valide d'avoir un autre formulaire qui soit imprimé :/

**Comment by lnplnp** [comment]
Bonjour,

J'ai vu cette v2, en fait... mais comme je n'ai pas vu le champ pour l'heure, je me suis dit que cette v2 était incomplète.

Es-tu sûr que si on imprime le document via ton formulaire, cela n'est pas recevable ?
En revanche, oui, il n'est pas valable si on montre une version numérique : via son téléphone par exemple.
Merci de m'avoir prévenu pour la recevabilité.

Merci.

Prend soin de toi !
Et reste chez toi... le plus longtemps possible !

**Comment by magopian** [comment]
> J'ai vu cette v2, en fait... mais comme je n'ai pas vu le champ pour l'heure, je me suis dit que cette v2 était incomplète.

Quand on clique sur le bouton "je sors de chez moi", ça affiche une popup qui indique depuis quand on est sorti automatiquement

> Es-tu sûr que si on imprime le document via ton formulaire, cela n'est pas recevable ?

Je ne suis sûr de rien, mais c'est ce qu'on m'a dit :/

> Prend soin de toi !
> Et reste chez toi... le plus longtemps possible !

Merci, toi aussi, et toi aussi ;)
