### ISSUE TITLE
Autofil date with JS

### ISSUE THREAD

**Issue by xgaia** [magopian/att#4]
Hello @magopian , Cool project.

I suggest to auto fill the date field with a little javascript

```html
<script type="text/javascript">
          var today = new Date();
          var mm = String(today.getDate()).padStart(2, '0');
          var dd = String(today.getMonth() + 1).padStart(2, '0'); //January is 0!
          var yyyy = today.getFullYear();

          today = mm + '/' + dd + '/' + yyyy;
          document.write(today);
</script>
```

I can make a PR

**Comment by magopian** [comment]
I thought about it, and yes it might be a useful addition.
We need to make sure though that this value is stored in the localStorage, even if the user never updates it!

Regarding the PR, sure, thanks! A heads up: I believe it should set the value of the date input
- only if there isn't a value already (to make sure we won't overwrite the value input by a user previously and restored from the localStorage)
- I believe the code could be simplified to
```javascript
new Date().toLocaleString().slice(0, 10)
```

**Comment by sunny** [comment]
Perhaps this shouldn't actually be a field, but stay up to date automatically?

**Comment by magopian** [comment]
Closing following my comments in #10
