### ISSUE TITLE
Données personnelles 

### ISSUE THREAD

**Issue by pachevalier** [magopian/att#6]
Quelles sont les informations sur les données connectées par cette app ? Tout se fait bien en local ou les données sont elles envoyées côté serveur ?

**Comment by magopian** [comment]
Tout se passe côté client, en local. Il n'y a aucune requête qui sorte ou qui entre. Pour s'en assurer, il suffit d'afficher le "code source de la page" une fois sur le site : raccourci clavier Cmd-u sous osx, Ctrl-u sous windows/linux, ou alors un clic droit sur la page et "code source de la page" sous firefox ou chrome.

**Comment by pachevalier** [comment]
Merci pour ta réponse mais mon point c'est qu'il faut le dire à l'usager sur le site parce que c'est pas évident.

**Comment by magopian** [comment]
Ah oui pardon j'avais pas compris ta demande, je réouvre.
Un collègue de l'incubateur du MAS est en train d'écrire des mentions légales pour le site, et je suis en train de réfléchir à comment avoir une popup explicative en arrivant sur le site, ou un moyen de l'afficher en cliquant sur un `?` ou un lien en bas de page...

**Comment by magopian** [comment]
@pYassine est en train de travailler sur ce sujet !

**Comment by magopian** [comment]
Et voilà c'est fait, merci encore à @pYassine qui nous a concocté une chouette popup d'info quand on arrive sur le site.
